version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:21.0.5'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

executors:
  j11:
    docker:
      - image: 'cimg/openjdk:21.0.5'

orbs:
  maven: circleci/maven@1.4.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j11
      - build:
          context: SonarCloud